### ISSUE TITLE
Module not found: Error: Cannot resolve module

### ISSUE THREAD

**Issue by ryan702** [mjackson/expect#125]
I also posted this question in the webpack git. I'm probably missing a configuration property, but this is what I'm getting when trying to build. It only happens when I try to import the expect library.

Error in ./~/tmatch/index.js
Module not found: Error: Cannot resolve module '**\\\\10.0.10.23**\dev\node_modules\process\browser.js' in **M:**\dev\node_modules\tmatch @ ./~/tmatch/index.js 1:0-89

My webpack.config.js:
```
module.exports = {
  entry: './src/app.js',
  output: {
    path: __dirname + '/build',
    filename: 'app.bundle.js'
  },
  module: {
    loaders: [{
      loader: 'babel-loader',
      test: /\.js$/,
      exclude: /node_modules/,
      query: {
        presets: ['es2015']
      }
    }]
  }
};
```

My package.json

```
"devDependencies": {
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "deep-freeze": "0.0.1",
    "eslint": "^3.0.1",
    "expect": "^1.20.2",
    "webpack": "^1.13.1"
},
```

**Comment by mjackson** [comment]
Hmm, it looks like one of our deps, `tmatch`, [checks `process.env.NODE_DEBUG`](https://github.com/tapjs/tmatch/blob/e228fa7d9fbb528e1d00580ff1281adfaa5958d5/index.js#L14) to know how to log errors. You could try setting that value using `webpack.DefinePlugin` to swap it out with a static value, like we do [in our build](https://github.com/mjackson/expect/blob/f0314f0d77fcced3560824a3f7f6b2c606d4a0ba/webpack.config.js#L16-L18). Hope that helps :)

Closing, since this is not an issue w `expect` AFAICT.
