### ISSUE TITLE
Oops someone published jest OVER expect on npm

### ISSUE THREAD

**Issue by possibilities** [mjackson/expect#226]
cc @cpojer

**Comment by cpojer** [comment]
Yes, that was intentional. It didn't publish Jest over expect, it published `jest-matchers` over `expect`. `jest-codemods` can be used to upgrade to the new version of expect, or otherwise please keep using the old version of expect if you like it better.

* Michael's Tweet: https://twitter.com/mjackson/status/904731413882191872
* Codemod: https://github.com/skovhus/jest-codemods
* PR in Jest: https://github.com/facebook/jest/pull/4345
* Issue in Jest: https://github.com/facebook/jest/issues/1679

**Comment by possibilities** [comment]
Oh wow, ok. Thanks!

**Comment by possibilities** [comment]
No holy war here but I do have to say that's a kinda bad surprise for a longtime expect user. That said I see there won't be that much effort to convert. For now I'll trust that it's a good decision for the larger community.

**Comment by skovhus** [comment]
@possibilities expect@21+ still supports the same features as expect@1.

https://github.com/skovhus/jest-codemods should make is possible to seamly upgrade. Please give it a try, and let me know if something is not working for you (create issue over at our repo).

Thanks : )
