### ISSUE TITLE
Don't assume name of node binary

### ISSUE THREAD

**Issue by gagern** [mjackson/expect#64]
Installing expect in a project on Debian or Ubuntu will fail because the `node` binary there is called `nodejs` not `node`, but the `postinstall` script in expect unconditionally tries to run `node`. Here is the output I got from a recent Ubuntu Xenial Docker:

```
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! expect@1.13.4 postinstall: `node ./npm-scripts/postinstall.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the expect@1.13.4 postinstall script 'node ./npm-scripts/postinstall.js'.
```

It seems that `npm` exports a `NODE` variable since https://github.com/npm/npm/commit/9c63b765a6d125324cf27ae01785e0d13ec62b9f i.e. for ages now, so you could change that `node` to `$NODE` and should be good. Not sure that works on Windows, so please test there.

**Comment by gagern** [comment]
Just for the record: I consider this `postinstall` script (which according to e001097ebbde706750aef9b726b6c68de1ff6f39 helps “installing from GitHub”) to be a dirty hack to work around https://github.com/npm/npm/issues/3055. But I can see the motivation to work around that for now. Just want to keep in mind that there may come a time when this script can be removed, since `prepublish` will do all that's required.

**Comment by mjackson** [comment]
@gagern npm's [prepublish doesn't do what it says it does](https://github.com/npm/npm/issues/3059), so we use postinstall instead. It's just there to create the `lib` directory in case someone installs directly from GitHub (e.g. using `npm install mjackson/expect`). https://github.com/npm/npm/issues/3055 will further expand upon the meaning of "prepublish" which makes me even more wary of using it. It's fixing stuff that's broken with more brokenness.

I'd be happy to consider a PR using `$NODE` instead of `node` provided we can find someone with a Windows machine to test it out.

**Comment by phated** [comment]
I think it is worth noting that if someone is using the `nodejs` binary on Ubuntu or Debian, they should probably get an error since (last I checked) the version of node those OSes shipped was 0.6 :cry:

**Comment by gagern** [comment]
@phated: There are more recent versions of Node on the way, most notably Node 4 in testing:
* jessie: 0.10.29~dfsg-2
* stretch: 4.2.6~dfsg-1
* precise: 0.6.12~dfsg1-1ubuntu1
* trusty, vivid and wily: 0.10.25~dfsg2-2ubuntu1
* xenial: 4.2.6~dfsg-1ubuntu1

**Comment by rstacruz** [comment]
> I think it is worth noting that if someone is using the nodejs binary on Ubuntu or Debian

even modern versions of node have their binaries set to `nodejs`. the workaround here is to use the `node-legacy` package (which despite its name, actually packages modern versions, only with its binary named as `node`)

**Comment by rstacruz** [comment]
> npm's prepublish doesn't do what it says it does, so we use postinstall instead.

Btw, [in-publish](https://www.npmjs.com/package/in-publish) exists as a workaround to this :)

**Comment by rstacruz** [comment]
@mjackson,

> It's just there to create the lib directory in case someone installs directly from GitHub (e.g. using npm install mjackson/expect).

To be fair, the workaround doesn't actually work when doing this:

```
npm install mjackson/expect
...
npm ERR! expect@1.14.0 build: `babel ./modules -d lib --stage 0 --loose all --ignore '__tests__'`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the expect@1.14.0 build script 'babel ./modules -d lib --stage 0 --loose all --ignore '__tests__''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the expect package,
```

IMHO, it's still moot to be using a `postinstall` script when a `prepublish` hook will do.

**Comment by mjackson** [comment]
> Btw, in-publish exists as a workaround to this

I've tried using `in-publish` before but AFAICT it gives Windows users problems because there is no `||` operator in CMD.exe, only `&&`, which makes it impossible to restrict code to only running when you are not actually running as a result of `npm publish` (i.e. in an `npm install`).

> the workaround doesn't actually work when doing this

Seems there's a bug.
