### ISSUE TITLE
Add tmatch support to expect(object).toMatch

### ISSUE THREAD

**Issue by elado** [mjackson/expect#81]
[tmatch](https://github.com/tapjs/tmatch) does a better job of deeply checking for a partial object in another.

Specifically with:
-  matching arrays and nested objects in arrays.
- comparing dates
- matching RegExp to a string

Should we change the code (as I PRed @ #80) to use it?

```js
tmatch(
  {a: 1, b: 2, c: {d: 4, e: {f: 5, g: 6}, h: 7}, i: [{j: 8}, {k: 9, l: 10}], m: 'hello' },
  { b: 2, c: {d: 4, e: {g: 6}}, i:[ {j: 8}, {k: 9} ], m: /ll/ }
)
```

**Comment by ljharb** [comment]
A PR that adds test cases that pass with `tmatch` but fail with the current implementation would be a good start.

**Comment by mjackson** [comment]
We already have a `toMatch` method. Maybe we should augment that with `tmatch`-style support instead of further modifying `toInclude`? IMO "include" methods should check the expected value is a subset of the actual value, respecting types. "match" methods make it more obvious that we support things like RegExp matches, ala `String.prototype.match`.
